# Generated by Django 6.0.3 on 2026-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_instauser_gender_alter_instauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
