# Generated by Django 5.2.13 on 2026-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_instauser_id_instapost_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instapost",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_post", to="myapp.instauser"
            ),
        ),
    ]
