# Generated by Django 5.2.13 on 2026-05-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_instapost_tagged_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUsers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="myapp.instauser",
                    ),
                ),
                (
                    "following_persons",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_person",
                        to="myapp.instauser",
                    ),
                ),
            ],
        ),
    ]
