# Generated by Django 5.2.13 on 2026-05-09 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_followusers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="followusers",
            old_name="following_persons",
            new_name="following_person",
        ),
    ]
