# Generated by Django 5.2.13 on 2026-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="message",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="notifications",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
