# Generated by Django 5.2.13 on 2026-05-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_notifications_message_notifications_read_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="post_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.instapost",
            ),
        ),
    ]
