# Generated by Django 5.2.13 on 2026-05-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_like_unlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="instauser",
            name="account_type",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=30,
            ),
        ),
    ]
