# Generated by Django 5.2.13 on 2026-05-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_instauser_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaReels",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="posts/")),
                ("caption", models.TextField(blank=True, null=True)),
                ("cover_page", models.FileField(upload_to="instaReels_thumbnails/")),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tagged_users",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_reels", to="myapp.instauser"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to="myapp.instauser",
                    ),
                ),
            ],
        ),
    ]
