# Generated by Django 5.2.13 on 2026-05-10 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_instareels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instareels",
            name="cover_page",
        ),
        migrations.RemoveField(
            model_name="instareels",
            name="location",
        ),
        migrations.RemoveField(
            model_name="instareels",
            name="tagged_users",
        ),
    ]
