# Generated by Django 5.2.13 on 2026-05-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_remove_instareels_cover_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaStory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="instastory/")),
                ("caption", models.CharField(blank=True, null=True)),
                ("music", models.FileField(upload_to="instamusic/")),
                ("story_text", models.CharField(blank=True, max_length=40, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.instauser",
                    ),
                ),
            ],
        ),
    ]
