# Generated by Django 5.2.13 on 2026-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_instastory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instastory",
            name="music",
            field=models.FileField(blank=True, null=True, upload_to="instamusic/"),
        ),
    ]
