# Generated by Django 5.2.13 on 2026-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_alter_instastory_music"),
    ]

    operations = [
        migrations.AddField(
            model_name="instauser",
            name="otp",
            field=models.PositiveIntegerField(default=456),
        ),
    ]
