# Generated by Django 5.2.13 on 2026-05-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_chatroom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_message", models.CharField(max_length=100)),
                ("image", models.FileField(blank=True, null=True, upload_to="")),
                ("video", models.FileField(blank=True, null=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatroom",
                        to="myapp.chatroom",
                    ),
                ),
            ],
        ),
    ]
