# Generated by Django 5.2.13 on 2026-05-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_rename_create_at_chatroom_created_at_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senderby",
                to="myapp.instauser",
            ),
        ),
    ]
